config/routes.rb
Rails.application.routes.draw do

  # 管理者用　URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 会員用　URL /users/sign_in...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  namespace :admin do
    resources :tastes, except: [:new, :show, :destroy]
    resources :categories, except: [:new, :show, :destroy]
    resources :tags, only: [:index] do
      patch :update_tag, on: :collection
      patch :withdrew_tag, on: :member
    end
  end

  # 会員側のルーティング
  scope module: :public do
    root 'homes#top'
    resources :posts do
      resources :favorites, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end
end

app/models/taste.rb
class Taste < ApplicationRecord
  has_many :posts
end

app/controllers/admin/tastes_controller.rb
class Admin::TastesController < ApplicationController

  def index
    @taste = Taste.new
    @tastes = Taste.all
  end
  
  def create
    @taste = Taste.new(taste_params)
    @taste.save
    redirect_to admin_tastes_path
  end
  
  def edit
    @taste = Taste.find(params[:id])
  end
  
  def update
    taste = Taste.find(params[:id])
    taste.update(taste_params)
    redirect_to admin_tastes_path
  end
  
  private
  
  def taste_params
    params.require(:taste).permit(:name)
  end
end

app/helpers/admin/tastes_helper.rb
module Admin::TastesHelper
end

app/views/admin/tastes/edit.html.erb
<div class="body">
  <div class="tastes__all">
    <h3>オモさ変更</h3>
    <div class="tastes__form">
      <%= form_with model:@taste, url:admin_taste_path, local:true do |f| %>
        <table>
          <tr>
            <th>オモさ名称</th>
            <th><%= f.text_field :name %></th>
            <th><%= f.submit "変更する" %></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tastes/index.html.erb
<div class="body">
  <div class="tastes__all">
    <h3>オモさ</h3>
    <div class="tastes__form">
      <!--オモさ追加機能-->
      <%= form_with model:@taste, url:admin_tastes_path, local:true do |f| %>
       <table>
         <tr>
           <th>オモさ名称追加</th>
           <th><%= f.text_field :name, placeholder: "オモさ名称" %></th>
           <th><%= f.submit "新規登録", class: "btn btn-2" %></th>
         </tr>
       </table>
      <% end %>
    </div>
    <div class="tastes__item">
      <!--オモさ一覧表示-->
      <table>
        <thead>
          <tr>
            <th>一覧</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @tastes.each do |taste| %>
            <tr>
              <td><%= taste.name %></td>
              <td><%= link_to "編集する", edit_admin_taste_path(taste), class: "btn btn-2" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>