config/routes.rb
Rails.application.routes.draw do

  # 管理者用　URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 会員用　URL /users/sign_in...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  namespace :admin do
    resources :tastes, except: [:new, :show, :destroy]
    resources :categories, except: [:new, :show, :destroy]
    resources :tags, only: [:index] do
      patch :update_tag, on: :collection
      patch :withdrew_tag, on: :member
    end
  end

  # 会員側のルーティング
  scope module: :public do
    root 'homes#top'
    resources :posts do
      resources :favorites, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tagmaps, dependent: :destroy
  has_many :posts, through: :tagmaps
  
  # 管理者側のカスタマイズ設定で、注目食材か表示食材のどちらの登録か判断するために使用する
  attr_accessor :selected_food

  # 入力されたタグ名が登録済みか探す
  def self.search_tag(name)
    Tag.find_by(tag_name: name)
  end

  # 注目食材か表示食材かを判断してアップデートする
  def self.update_display_tag(searched_tag, selected_food)
    if selected_food === "display_food"
      searched_tag.update(display_food: true)
    else
      searched_tag.update(pickup_food: true)
    end
  end
  
  # 注目食材か表示食材かを判断して項目から外す
  def self.withdrew_display_tag(selected_tag, selected_food)
    if selected_food == "display_food"
      selected_tag.update(display_food: false)
    else
      selected_tag.update(pickup_food: false)
    end
  end
  
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def index
    @display_food = Tag.where(display_food: true)
    @pickup_food = Tag.where(pickup_food: true)
  end

  # トップページに表示する食品タグと注目食材の設定
  def update_tag
    searched_tag = Tag.search_tag(tag_params[:tag_name])

    if searched_tag
      Tag.update_display_tag(searched_tag, tag_params[:selected_food])
      redirect_to request.referer
    else
      redirect_to request.referer, notice: 'そのタグは未登録です'
    end
  end
  
  def withdrew_tag
    selected_tag = Tag.find(params[:id])
    
    if selected_tag
      Tag.withdrew_display_tag(selected_tag, tag_params[:selected_food])
      redirect_to admin_tags_path, notice: '更新しました'
    else
      redirect_to admin_tags_path
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name, :pickup_food, :display_food, :selected_food)
  end

end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/index.html.erb
<div class="body">
  <div class="admintop__all">
    <h3>トップページ食材のカスタマイズ設定</h3>
    <div class="admintop__form">

      <%= form_with model: Tag, url: update_tag_admin_tags_path, method: :patch, local:true do |f| %>
        <table>
          <tr>
            <th><%= f.text_field :tag_name, placeholder: "食材名" %></th>
            <th><%= f.select :selected_food, options_for_select({ "注目食材" => "pickup_food", "表示食材タグ" => "display_food" }) %></th>
            <th><%= f.submit "追加", class: 'btn btn-2' %></th>
          </tr>
        </table>
      <% end %>
    </div>
      <!--注目食材を使った投稿を表示させるためのタグ登録-->
    <div class="admintop__tag">
      <table>
        <thead>
          <tr>
            <th>注目食材一覧</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @pickup_food.each do |pickup_food| %>
            <tr>
              <th>
                <%= pickup_food.tag_name %>
              </th>
              <th>
                <%= form_with model: Tag, url: withdrew_tag_admin_tag_path(pickup_food), method: :patch, local:true do |f| %>
                  <%= f.hidden_field :selected_food, :value => "pickup_food" %>
                  <%= f.submit "注目から外す", class: 'btn btn-2' %>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <!--トップページ上部に表示させる食材名のタグ登録-->
      <table>
        <thead>
          <tr>
            <th>表示食材タグ</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @display_food.each do |display_food| %>
            <tr>
              <th>
                <%= display_food.tag_name %>
              </th>
              <th>
                <%= form_with model: Tag, url: withdrew_tag_admin_tag_path(display_food), method: :patch, local:true do |f| %>
                  <%= f.hidden_field :selected_food, :value => "display_food" %>
                  <%= f.submit "表示から外す", class: 'btn btn-2' %>
                <% end %>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>