config/routes.rb
Rails.application.routes.draw do

  # 管理者用　URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 会員用　URL /users/sign_in...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  namespace :admin do
    resources :tastes, except: [:new, :show, :destroy]
    resources :categories, except: [:new, :show, :destroy]
    resources :tags, only: [:index] do
      patch :update_tag, on: :collection
      patch :withdrew_tag, on: :member
    end
  end

  # 会員側のルーティング
  scope module: :public do
    root 'homes#top'
    resources :posts do
      resources :favorites, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to admin_categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to admin_categories_path
  end

  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="body">
  <div class="categories__all">
    <h3>カテゴリー編集</h3>
    <div class="categories__form">
      <%= form_with model:@category, url:admin_category_path, local:true do |f| %>
      <table>
        <tr>
          <th>カテゴリー名</th>
          <th><%= f.text_field :name %></th>
          <th><%= f.submit"変更する", class: "btn btn-2" %></th>
        </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="body">
  <div class="categories__all">
    <h3>料理カテゴリー</h3>
    <div class="categories__form">
      <!--カテゴリー追加機能-->
      <%= form_with model:@category, url:admin_categories_path, local:true do |f| %>
       <table>
        <tr>
          <th>料理カテゴリー追加</th>
          <th><%= f.text_field :name, placeholder: "新しいカテゴリー名" %></th>
          <th><%= f.submit"追加", class: "btn btn-2" %></th>
        </tr>
       </table>
      <% end %>
    </div>
    <div class="categories__item">
      <!--登録済みカテゴリーの表示-->
      <table>
        <thead>
          <tr>
            <th>一覧</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= link_to "編集する", edit_admin_category_path(category), class: "btn btn-2" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>