config/routes.rb
Rails.application.routes.draw do

  # 管理者用　URL /admin/sign_in...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # 会員用　URL /users/sign_in...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # 管理者側のルーティング
  namespace :admin do
    resources :tastes, except: [:new, :show, :destroy]
    resources :categories, except: [:new, :show, :destroy]
    resources :tags, only: [:index] do
      patch :update_tag, on: :collection
      patch :withdrew_tag, on: :member
    end
  end

  # 会員側のルーティング
  scope module: :public do
    root 'homes#top'
    resources :posts do
      resources :favorites, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      get :favorites, on: :collection
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <% if current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
    <div class="footer__login">
      <p>nanitaberu? since2022</p>
    </div>
  <% else %>
    <!--フッターーロゴ-->
    <%= image_tag 'footer.png', class: "footer__img" %>
    <div class="footer__global">
      <p>nanitaberu? since2022</p>
    </div>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header>
 <!--ヘッダーロゴ-->
  <%= link_to root_path do %>
   <%= image_tag 'logo.png', alt: 'logo', class: 'header__logo' %>
  <% end %>
  <!--ハンバーガーメニュー-->
  <input id="menu" type="checkbox">
  <label for="menu" class="menu__open">menu</label>
  <label for="menu" class="menu__back"></label>
  
  <% if user_signed_in? %>
    <label for="menu" class="menu__close"></label>

    <nav class="header__nav">
      <ul>
        <li>
          <%= link_to "マイページ", user_path(current_user), class: "header__nav_item fas fa-house-user" %>
        </li>
        <li>
          <%= link_to "新規投稿", new_post_path, class: "header__nav_item fas fa-plus-square" %>
        </li>
        <li>
          <%= link_to "投稿一覧", posts_path, class: "header__nav_item fas fa-utensils" %>
        </li>
        <li>
          <%= link_to "お気に入り", post_favorites_path(current_user), class: "header__nav_item fas fa-star" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "header__nav_item fas fa-door-closed" %> 
        </li>
      </ul>
    </nav>
    
  <% elsif admin_signed_in? %>
    <label for="menu" class="back"></label>

    <nav class="header__nav">
      <ul>
       
        <li>
          <%= link_to "カテゴリー", admin_categories_path, class: "header__nav_item" %>
        </li>
        <li>
          <%= link_to "オモさ", admin_tastes_path, class: "header__nav_item" %>
        </li>
        <li>
          <%= link_to "トップページ設定", admin_tags_path, class: "header__nav_item" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "header__nav_item" %>
        </li>
      </ul>
    </nav>
    
  <% else %>
    <label for="menu" class="back"></label>

    <nav class="header__nav">
      <ul>
        <li>
          <%= link_to "投稿一覧", posts_path, class: "header__nav_item fas fa-utensils" %>
        </li>
        <li>
          <%= link_to "新規登録", new_user_registration_path, class: "header__nav_item fas fa-plus-square" %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path, class: "header__nav_item fas fa-sign-in-alt" %>
        </li>
      </ul>
    </nav>
    
  <% end %>

</header>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ナニタベル</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!--font-awesome読み込み-->
    <script src="https://kit.fontawesome.com/a8d8b5ebb4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
      <!--エラーメッセージの表示-->
      <% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path) || current_page?(new_admin_session_path) then %>
        <p class="notice">
          <%= notice %>
        </p>
      <% end %>


    <%= yield %>

    <span id="page__top">
      <a href="">
        <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: 'arrow' %>
      </a>
    </span>

    <%= render 'layouts/footer' %>
  </body>

</html>